name: srv_paperless
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  bcrypt: ^1.2.0
  flutter_dotenv: ^6.0.0
  google_fonts: ^8.0.1
  flutter_riverpod: ^3.2.0
  mysql1: ^0.20.0
  minio: ^3.5.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  intl: ^0.20.2
  file_picker: ^10.3.10
  image_picker: ^1.2.1
  firebase_storage: ^13.0.6
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

  fonts:
    - family: BaiJamjuree
      fonts:
        - asset: assets/fonts/BaiJamjuree/BaiJamjuree-Bold.ttf
        - asset: assets/fonts/BaiJamjuree/BaiJamjuree-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/BaiJamjuree/BaiJamjuree-ExtraLight.ttf
        - asset: assets/fonts/BaiJamjuree/BaiJamjuree-ExtraLightItalic.ttf
          style: italic
        - asset: assets/fonts/BaiJamjuree/BaiJamjuree-Italic.ttf
          style: italic
        - asset: assets/fonts/BaiJamjuree/BaiJamjuree-Light.ttf
        - asset: assets/fonts/BaiJamjuree/BaiJamjuree-LightItalic.ttf
          style: italic
        - asset: assets/fonts/BaiJamjuree/BaiJamjuree-Medium.ttf
        - asset: assets/fonts/BaiJamjuree/BaiJamjuree-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/BaiJamjuree/BaiJamjuree-Regular.ttf
        - asset: assets/fonts/BaiJamjuree/BaiJamjuree-SemiBold.ttf
        - asset: assets/fonts/BaiJamjuree/BaiJamjuree-SemiBoldItalic.ttf
          style: italic